### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/crab#23]
1. Move to top of readme
2. Document commands needed to install from GitHub (virtual env etc)
3. Note about running `chmod +x ./path/crab` to make executable

...or fix the binary?

**Comment by j4mie** [comment]
2 is now done and 3 is redundant. I actually like the installation instructions being at the bottom - they’re quite long, and I’d rather people knew what crab does before getting on to how to install it.
